-- MySQL Script generated by MySQL Workbench
-- 02/26/16 13:45:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sysmodel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sysmodel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysmodel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sysmodel` ;

-- -----------------------------------------------------
-- Table `sysmodel`.`typeuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysmodel`.`typeuser` (
  `id_typeuser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_typeuser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysmodel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysmodel`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `count_login` INT NULL,
  `date` DATE NULL,
  `id_typeuser` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_typeuser_idx` (`id_typeuser` ASC),
  CONSTRAINT `fk_user_typeuser`
    FOREIGN KEY (`id_typeuser`)
    REFERENCES `sysmodel`.`typeuser` (`id_typeuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysmodel`.`typepost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysmodel`.`typepost` (
  `id_typepost` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_typepost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysmodel`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysmodel`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `date` DATE NULL,
  `views` INT NULL,
  `id_typepost` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_post_typepost1_idx` (`id_typepost` ASC),
  INDEX `fk_post_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_post_typepost1`
    FOREIGN KEY (`id_typepost`)
    REFERENCES `sysmodel`.`typepost` (`id_typepost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sysmodel`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
